### ISSUE TITLE
CUDA driver error when using TorchForce combined with MTSLangevinIntegrator and reporters

### ISSUE THREAD

**Issue by Hong-Rui** [openmm/openmm#3588]
Hi @raimis and @peastman 

I met a weird error when I'm testing some NN Potential + MD things. 
And I'm using the latest master branch of OpenMM due to the `setVelocityToTemperature` problem with `TorchForce`
https://github.com/openmm/openmm-torch/issues/61

Basically, we design a torch force that evaluates the CV potential and forces as a bias force object added to the system.
We're trying to do the biased MD with `MTSLangevinIntegrator` , we design that the NN force should evaluate at, say,  dt=20 fs while for any other forces dt=4 fs with HMR. The reason we try to do MTS with NN force is due to the simulation speed.

Everything goes fine when I run the simulation without any reporters, but when I added the `StateDataReporter` and `DCDReporter`, the simulation failed immediately when it tries to get information from the context during `_generate_reports`.

Here is the example script of what I'm trying to do:

```python
structure = pmd.load_file('chignolin.prmtop', xyz='chignolin.inpcrd')
system = structure.createSystem(nonbondedMethod=PME,
                                                     nonbondedCutoff=12.0 * angstrom,
                                                    constraints=HBonds,
                                                    hydrogenMass=3.024)

num_forces = system.getNumForces()
force_group_list = [None] * num_forces

for force_idx in range(num_forces):
    force = system.getForce(force_idx)
    force_group = force.getForceGroup()
    force_group_list[force_idx] = force_group

unique_force_group_array = np.unique(np.sort(force_group_list))
torch_force_group = np.max(unique_force_group_array) + 1

integrator_step_tuple_list = []
for force_group in unique_force_group_array:
    integrator_step_tuple_list.append((force_group, 5))

integrator_step_tuple_list.append((torch_force_group, 1))

## [(0, 5), (1, 5), (2, 5), (11, 5), (12, 1)]
## force group 12 is for torch force, while 0, 1, 2, 11 for other normal MD force.

integrator = MTSLangevinIntegrator(298.15 * kelvin, 1.0 / picosecond, 0.020 * picoseconds, integrator_step_tuple_list)

platform = Platform.getPlatformByName('CUDA')
platform_property = {'Precision': 'mixed', 'DisablePmeStream': 'true', 'DeviceIndex': '6'}

simulation = Simulation(structure.topology, system, integrator, platform, platform_property)
simulation.context.setPositions(structure.positions)


#############################################
## Some long Torch Script treatment to build the torch force 
## After this, you get a TorchForce object

torch_force = TorchForce('model_torch_nn_test.pt')
torch_force.setOutputsForces(True)
torch_force.setForceGroup(torch_force_group)
#############################################

state = simulation.context.getState(getPositions=True,getVelocities=True)
coords = state.getPositions(asNumpy=True)
box_vectors = state.getPeriodicBoxVectors()

barostat(system=system,
         temp=298.15 * kelvin,
         p_ref=1.0 * bar,
         p_type='isotropic',
         p_scale=[True, True, True],
         p_xy_mode=None,
         p_z_mode=None,
         p_tens=0.0 * bar * nanometers,
         p_freq=25)

# Add the TorchForce to your System
system.addForce(torch_force)

simulation.context.reinitialize()
simulation.context.setPositions(coords)
simulation.context.setPeriodicBoxVectors(*box_vectors)

# Generate initial velocities (this works fine with master branch openmm)
simulation.context.setVelocitiesToTemperature(298.15)

print("\nMD NPT production run: %s steps" % 250000)
simulation.reporters = []
simulation.context.setTime(0)
simulation.currentStep = 0

state_data_reporter = StateDataReporter('chignolin_bias_4.out',
                                                                  200,
                                                                  step=True,
                                                                  time=True,
                                                                  potentialEnergy=True,
                                                                  temperature=True,
                                                                  kineticEnergy=True,
                                                                  totalEnergy=True,
                                                                  speed=True,
                                                                  separator='\t',
                                                                  progress=True,
                                                                  remainingTime=True,
                                                                  totalSteps=250000)

dcd_reporter = DCDReporter('chignolin_bias_4.dcd', 200)

simulation.reporters.append(state_data_reporter)
simulation.reporters.append(dcd_reporter)

simulation.step(250000)
```

The error reports:
```python
---------------------------------------------------------------------------
OpenMMException                           Traceback (most recent call last)
Input In [26], in <cell line: 25>()
     22 simulation.reporters.append(state_data_reporter)
     23 simulation.reporters.append(dcd_reporter)
---> 25 simulation.step(250000)

File /home/corp/hongrui.lin/Modules/miniconda3/envs/drug_design/lib/python3.9/site-packages/openmm/app/simulation.py:141, in Simulation.step(self, steps)
    139 def step(self, steps):
    140     """Advance the simulation by integrating a specified number of time steps."""
--> 141     self._simulate(endStep=self.currentStep+steps)

File /home/corp/hongrui.lin/Modules/miniconda3/envs/drug_design/lib/python3.9/site-packages/openmm/app/simulation.py:241, in Simulation._simulate(self, endStep, endTime)
    238 # Generate the reports.
    240 if len(wrapped) > 0:
--> 241     self._generate_reports(wrapped, True)
    242 if len(unwrapped) > 0:
    243     self._generate_reports(unwrapped, False)

File /home/corp/hongrui.lin/Modules/miniconda3/envs/drug_design/lib/python3.9/site-packages/openmm/app/simulation.py:259, in Simulation._generate_reports(self, reports, periodic)
    257     if next[4]:
    258         getEnergy = True
--> 259 state = self.context.getState(getPositions=getPositions, getVelocities=getVelocities, getForces=getForces,
    260                               getEnergy=getEnergy, getParameters=True, enforcePeriodicBox=periodic,
    261                               groups=self.context.getIntegrator().getIntegrationForceGroups())
    262 for reporter, next in reports:
    263     reporter.report(self, state)

File /home/corp/hongrui.lin/Modules/miniconda3/envs/drug_design/lib/python3.9/site-packages/openmm/openmm.py:8889, in Context.getState(self, getPositions, getVelocities, getForces, getEnergy, getParameters, getParameterDerivatives, getIntegratorParameters, enforcePeriodicBox, groups)
   8887 if getIntegratorParameters:
   8888     types += State.IntegratorParameters
-> 8889 state = _openmm.Context_getState(self, types, enforcePeriodicBox, groups_mask)
   8890 return state

OpenMMException: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: CUDA driver error: invalid resource handle
```

I guess this is probably related to some CUDA kernel stuff again similar to https://github.com/openmm/openmm-torch/issues/61

BTW, I also tested this protocol with normal `LangevinMiddleIntegrator` combined with reporters, everything works fine.
So the problem only appears when using torch force combined with MTS integrators and reporters.

Thanks a lot!

Regards

**Comment by Hong-Rui** [comment]
Hello~ @peastman 
Is this issue going to be fixed?
Or are there ways that I can work around with this?

Thanks a lot !!

**Comment by Hong-Rui** [comment]
By further investigating this problem, we found that, if we tune the `potentialEnergy`, `temperature`, `kineticEnergy`, and `totalEnergy` options to `False` in the `StateDataReporter`， that means to avoid `getState`, then the error disappears.

```python
print("\nMD NPT production run: %s steps" % 250000)
simulation.reporters = []
simulation.context.setTime(0)
simulation.currentStep = 0

state_data_reporter = StateDataReporter('chignolin_bias_4.out',
                                        200,
                                        step=True,
                                        time=True,
                                        potentialEnergy=False,
                                        temperature=False,
                                        kineticEnergy=False,
                                        totalEnergy=False,
                                        speed=True,
                                        separator='\t',
                                        progress=True,
                                        remainingTime=True,
                                        totalSteps=250000)

dcd_reporter = DCDReporter('chignolin_bias_4.dcd', 200)

simulation.reporters.append(state_data_reporter)
simulation.reporters.append(dcd_reporter)

simulation.step(250000)
```

Seems that things going wrong when it is trying to get some stuff from the cuda kernels?

And this does not affect the use of `DCDReproter`, probably seems that it does not need to extract positions from the cuda?

Hope this helps,

Thanks

**Comment by peastman** [comment]
@raimis do you have any idea about this?  It looks like an error inside PyTorch while trying to evaluate the model.

**Comment by raimis** [comment]
@Hong-Rui could make a dummy model (i.e. always returns zeros) and test?

**Comment by Hong-Rui** [comment]
@raimis Hello, I just tested the dummy model, everything works fine. Weird.

The model definition is super simple like this:
```python
class ForceModule(torch.nn.Module):
    def __init__(self, torch_device):
        super(ForceModule, self).__init__()
        self.torch_device = torch_device

    def forward(self, positions):
        num_atoms = positions.shape[0]
        energy_tensor = torch.tensor(0.0, dtype=torch.float64, device=self.torch_device)
        force_tensor = torch.zeros((num_atoms, 3), dtype=torch.float64, device=self.torch_device)

        return energy_tensor, force_tensor
```

**Comment by peastman** [comment]
Is it possible this is a downstream effect of some other error on the GPU, such as running out of device memory?

**Comment by raimis** [comment]
Soon there will be a OpenMM-Torch pacakge for PyTorch 1.11 (https://github.com/conda-forge/openmm-torch-feedstock/pull/17). It might help, if you hitting some bug of PyTorch.

**Comment by raimis** [comment]
As you don't share the comple script and input files (including your model), I cannot reproduce the issue.

**Comment by Hong-Rui** [comment]
Hello, I just come up with a minimal working failing example of this.
After some trial, it seems that it is the torch jit scripts that is causing the issue. When the `TorchForce` module calls the external functions written in torch jit script, it may lead to this kind of cuda error, only when using `MTSLangevinIntegrator` combined with `getState` called during generate reports.

In this example, I dropped out all the NN models and CV chain rule calculations, and just did some very simple and random calculations that basically do not make any sense at all. However, in this simple calculations I can reproduce the same error.

Please find the attached input files and run scripts to reproduce this, hope this is helpful for finding the problems!

[reproduce_mts_issue.zip](https://github.com/openmm/openmm/files/8735654/reproduce_mts_issue.zip)

**Comment by Hong-Rui** [comment]
Hello, I just come up with a minimal working failing example of this.
After some trial, it seems that it is the torch jit scripts that is causing the issue. When the `TorchForce` module calls the external functions written in torch jit script, it may lead to this kind of cuda error, only when using `MTSLangevinIntegrator` combined with `getState` called during generate reports.

In this example, I dropped out all the NN models and CV chain rule calculations, and just did some very simple and random calculations that basically do not make any sense at all. However, in this simple calculations I can reproduce the same error.

Please find the attached input files and run scripts to reproduce this, hope this is helpful for finding the problems!
[chignolin.zip](https://github.com/openmm/openmm/files/8735681/chignolin.zip)

**Comment by peastman** [comment]
Could you simplify it to something without so many dependencies?  I don't even know what `xdalgorithm` is or how to install it.  And MDAnalysis has dozens of dependencies that will make a mess of my development environment.

**Comment by Hong-Rui** [comment]
Oops, my mistake.
Sorry that I forgot to clean all these unnecessary dependencies.

Please find the attached scripts to reproduce this issue.

[chignolin.zip](https://github.com/openmm/openmm/files/8747378/chignolin.zip)

**Comment by peastman** [comment]
Thanks!  I'm able to reproduce it.  I'll investigate and see if I can figure out what's going on.

I assume it's intentional that your model always returns constant forces and energies, independent of the positions?

**Comment by peastman** [comment]
The problem seems to be in this line:

```python
dihedral_value_array = torch.ones((self.num_dihedrals), dtype=torch.float64, device=self.torch_device)
```

If I remove the `device` attribute the error goes away.  I don't think it's correct to be specifying a device for local variables created inside the compiled module.  You want to let it create the tensor on whatever device the code is executing on.

**Comment by Hong-Rui** [comment]
> Thanks! I'm able to reproduce it. I'll investigate and see if I can figure out what's going on.
> 
> I assume it's intentional that your model always returns constant forces and energies, independent of the positions?

Yes, it's just for the test. In the real protocol, the NN CV forces absolutely depend on the positions of each frame.


> The problem seems to be in this line:
> 
> ```python
> dihedral_value_array = torch.ones((self.num_dihedrals), dtype=torch.float64, device=self.torch_device)
> ```
> 
> If I remove the `device` attribute the error goes away. I don't think it's correct to be specifying a device for local variables created inside the compiled module. You want to let it create the tensor on whatever device the code is executing on.

I've tested this before, but my requirement is to be able to run this on a specified cuda device.
There are multiple GPUs on our machine, and if I don't specify the cuda device when creating new tensor inside the `ForceModule`, then the created tensor will be on the CPU, and you would get a pytorch error says: found two conflicted devices: cpu and cuda:x.

In any way, it's very strange that the same code works for `LangivinMiddleIntegrator`, but not for `MTSLangivinIntegrator`.

**Comment by jchodera** [comment]
@peastman : Should we label this as a `bug` that should be addressed before the next release?

**Comment by peastman** [comment]
There's something strange going on with CUDA contexts.  When the plugin gets called from `step()`, one context is on the top of the stack.  But when it gets called from `getState()`, a different one is, and that's when the error occurs.  I haven't figured out where it's getting changed.  This might be related to https://github.com/openmm/openmm-ml/issues/25, where PyTorch wasn't managing the stack correctly.  I'll keep investigating.

**Comment by Hong-Rui** [comment]
Hi @peastman, thank you for pointing out this!
I actually met the same error as https://github.com/openmm/openmm-ml/issues/25 before. What I was doing was to build a NN model and load an `model.pt` file as the state dict for model parameters, and then use this NN model as a NN force in MD.

Our machine has multiple GPU cards, and I need to run multiple NN MD simulations at different GPUs, so the torch device idx for the NN model may not be 0. I originally trained the model on some arbitrary cuda device (but not 0!) and when I load back the parameters to built the NN torch force object, I encounter the `CUDA_ERROR_INVALID_HANDLE` error.

The way I can work around this is to always manually specify the map_location of state dict to be `cuda:0`.
A sample script looks like:
```python
    num_dihedrals = len(dihedral_atom_idx_nested_list)
    num_nn_models = len(model_parameter_file_name_list)
    model_list = [None] * num_nn_models
    cuda_device_string = 'cuda:' + str(cuda_device_idx)
    torch_device = torch.device(cuda_device_string)
    reference_torch_device = torch.device('cuda:0')

    dihedral_atom_idx_tensor = torch.tensor(dihedral_atom_idx_nested_list, dtype=torch.int64, device=torch_device)
    nn_model_config = set_conf(cv_dim_list=[num_dihedrals, 0],
                               neurons=[300, 300, 300, 300])

    for model_idx in range(num_nn_models):
        model_file_name = model_parameter_file_name_list[model_idx]
        model = Model(nn_model_config).to(torch_device)
        checkpoint = torch.load(model_file_name, map_location=reference_torch_device)
        model.load_state_dict(checkpoint)
        model_list[model_idx] = model

    module_list = nn.ModuleList(model_list)
    force_module = torch.jit.script(DihedralNNForce(dihedral_atom_idx_tensor,
                                                    torch_device,
                                                    module_list,
                                                    uncertainty_lower_level,
                                                    uncertainty_upper_level))

    force_module.save(force_module_file_name)

    torch_force = TorchForce(force_module_file_name)
    torch_force.setOutputsForces(True)
    torch_force.setForceGroup(torch_force_group)
    system.addForce(torch_force)
```

That is, despite the device I execute the model, the checkpoint data must be pointed to `cuda:0`. So when you do the NN MD simulation, there will actually be two cuda devices being used by OpenMM.

Hope this helps!

**Comment by peastman** [comment]
I've sort of found a workaround, but I don't really understand what's going on and I'm not sure it's correct.  When executing a step with CustomIntegrator, it first pushes the CUDA context onto the stack with `cuCtxPushCurrent()`.  It then calls `calcForcesAndEnergy()`, which pushes a second copy of the same context onto the stack.  I find that if I pop the context off the stack before calling `calcForcesAndEnergy()`, then push it back on when it returns, the error disappears.

But why would that matter?  There's nothing wrong with having multiple copies of the context on the stack.

I also found that the problem is related to calling `reinitialize()` on the context.  The error only happens after reinitializing.  If I remove that call, it doesn't happen.  Perhaps it's related to how PyTorch uses CUDA contexts.  Maybe it tries to adopt the context OpenMM has already created and use it for its own purposes?  Then when we destroy the context, it causes PyTorch to encounter errors.  This is just a hypothesis.

**Comment by raimis** [comment]
@peastman could you reopen this, so we don't loose the track.

**Comment by jchodera** [comment]
@hong-rui : Can you confirm the latest release fixes this? If so, can you close this?

**Comment by Hong-Rui** [comment]
Hello, I've just tested the new conda-force build of openmm-torch, and the latest master branch of openmm, and it works!

Thanks for your effort on this issue.
